services:
  web:
    build: ./web
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
    environment:
      API_URL: http://backend:8000
    depends_on:
      - backend
    command: yarn dev

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE:-postgres}
      DATABASE_HOST: ${DATABASE_HOST:-database}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-123}
      DATABASE_NAME: ${DATABASE_NAME:-forum_app}
      JWT_SECRET: ${JWT_SECRET:-supersecret}
    depends_on:
      - database
    command: yarn dev

  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-123}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-forum_app}
