services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      API_URL: http://backend:8000
    depends_on:
      - backend
    command: yarn dev

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: forum_app
      JWT_SECRET: supersecret
    depends_on:
      - database
    command: yarn dev

  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: forum_app
